[package]
authors = ["Ben Ruijl <benruyl@gmail.com>"]
categories = ["science"]
description = "A blazing fast computer algebra system with community enhancements"
edition = "2021"
keywords = ["algebra", "symbolic", "manipulation", "mathematics", "physics"]
license = "MIT"
name = "symbolica_community"
readme = "Readme.md"
repository = "https://github.com/benruijl/symbolica-community"
rust-version = "1.73"
version = "0.1.0"

[features]

default = [ "spenso", "algebraic_simplification", "vakint"]
algebraic_simplification = ["dep:spenso", "dep:spenso-macros"]
vakint = ["dep:vakint"]
spenso = ["dep:spenso"]

[profile.release]
codegen-units = 1
lto = true

[profile.dev-optim]
inherits = "dev"
opt-level = 3

[[bin]]
name = "stub_gen"
doc = false

[lib]
name = "symbolica_community"
crate-type = ["lib", "cdylib"]

[dependencies]
symbolica = { version = "0.16.0", features = ["python_no_module"] }
pyo3 = { version = "0.23.0", features = ["abi3-py37", "anyhow", "num-complex"] }

anyhow = "*"
vakint = { git = "https://github.com/alphal00p/vakint", branch = "vk_for_sb_0_16_latest", optional=true }
spenso = { version = "0.4.1", optional = true, features = ["shadowing"] }
itertools = "0.13.0"
delegate = "0.13.1"
auto_enums = "0.8.6"
thiserror = "1.0.65"
pyo3-stub-gen = "0.7.0"
env_logger = "0.11.5"

spenso-macros = {git="https://github.com/alphal00p/spenso",rev="90969b43462c4cf042611977036104562a09c699",features=["shadowing"],optional=true}

# spenso-macros = {path = "../spenso/spenso-macros"}
[patch.crates-io]
symbolica = { git = "https://github.com/benruijl/symbolica", rev = "57f25f34928ca667bd5889d94ed616d15e2ad94f" }
# spenso = { path = "../spenso/spenso" ,features = ["shadowing"] }
spenso={git="https://github.com/alphal00p/spenso",rev="90969b43462c4cf042611977036104562a09c699"}
# symbolica={git="https://github.com/alphal00p/symbolica",rev="d1e34cbadce9c7b196063d92602c7a15ca2305b2"}
