# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class CompiledTensorEvaluator:
    r"""
    A compiled and optimized evaluator for tensors.
    """
    ...

class Representation:
    r"""
    A representation class in the sense of representation theory. This class is used to represent the representation of a tensor. It is essentially a pair of a name and a dimension.
    New representations are registered when constructing.
    Some representations are dualizable, meaning that they have a dual representation.
    Indices will only ever match across dual representations.
    There are some already registered representations, such as:
     EUCLIDEAN: Rep = Rep::SelfDual(0);
     BISPINOR: Rep = Rep::SelfDual(1);
     COLORADJ: Rep = Rep::SelfDual(2);
     MINKOWSKI: Rep = Rep::SelfDual(3);
    
     LORENTZ_UP: Rep = Rep::Dualizable(1);
     LORENTZ_DOWN: Rep = Rep::Dualizable(-1);
     SPINFUND: Rep = Rep::Dualizable(2);
     SPINANTIFUND: Rep = Rep::Dualizable(-2);
     COLORFUND: Rep = Rep::Dualizable(3);
     COLORANTIFUND: Rep = Rep::Dualizable(-3);
     COLORSEXT: Rep = Rep::Dualizable(4);
     COLORANTISEXT: Rep = Rep::Dualizable(-4);
    """
    ...

class Slot:
    r"""
    An abstract index slot for a tensor.
    This is essentially a tuple of a `Representation` and an abstract index id.
    
    The abstract index id can be either an integer or a symbol.
    This is the building block for creating tensor structures that can be contracted.
    """
    ...

class Tensor:
    r"""
    A tensor class that can be either dense or sparse.
    The data is either float or complex or a symbolica expression
    It can be instantiated with data using the `sparse_empty` or `dense` module functions.
    """
    ...

class TensorEvaluator:
    r"""
    An optimized evaluator for tensors.
    """
    ...

class TensorIndices:
    r"""
    A structure that can be used to represent the "shape" of a tensor, along with a list of abstract indices.
    This has an optional name, and accompanying symbolica expressions that are considered as additional non-indexed arguments.
    The structure is essentially a list of `Slots` that are used to define the structure of the tensor.
    """
    ...

class TensorLibrary:
    ...

class TensorNetwork:
    r"""
    A tensor network.
    
    This class is a wrapper around the `TensorNetwork` class from the `spenso` crate.
    Such a network is a graph representing the arithmetic operations between tensors.
    In the most basic case, edges represent the contraction of indices.
    """
    ...

class TensorStructure:
    r"""
    A structure that can be used to represent the "shape" of a tensor.
    This has an optional name, and accompanying symbolica expressions that are considered as additional non-indexed arguments.
    The structure is essentially a list of `Representation` that are used to define the structure of the tensor.
    """
    ...

def dense(structure:typing.Any, data:typing.Any) -> Tensor:
    r"""
    Create a new dense tensor with the given structure and data.
    The structure can be a list of integers, a list of representations, or a list of slots.
    In the first two cases, no "indices" are assumed, and thus the tensor is indexless (i.e.) it has a shape but no proper way to contract it.
    The structure can also be a proper `TensorIndices` object or `TensorStructure` object.
    
    The data is either a list of floats or a list of symbolica expressions, of length equal to the number of elements in the structure, in row-major order.
    """
    ...

def sparse_empty(structure:typing.Any, type_info:type) -> Tensor:
    r"""
    Create a new sparse empty tensor with the given structure and type.
    The structure can be a list of integers, a list of representations, or a list of slots.
    In the first two cases, no "indices" are assumed, and thus the tensor is indexless (i.e.) it has a shape but no proper way to contract it.
    The structure can also be a proper `TensorIndices` object or `TensorStructure` object.
    
    The type is either a float or a symbolica expression.
    """
    ...

