# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import symbolica_community.tensors
from enum import Enum, auto

class TensorNamespace(Enum):
    Weyl = auto()
    Algebra = auto()

def to_net(a:Expression, library:TensorLibrary) -> TensorNetwork:
    ...
